SPACE_WIDTH = 100
SPACE_HEIGHT = 100
INITIAL_POPULATION = 250
MAX_SPEED = 2.5
TIME_STEP = 1 / 25
MAX_STEPS = 10000

SPAWN_INFECTED_PROBABILITY = 0.1
INITIAL_IMMUNE_PROBABILITY = 0.5
INITIAL_SUSCEPTIBLE_PROBABILITY = 0.5

assert INITIAL_IMMUNE_PROBABILITY + INITIAL_SUSCEPTIBLE_PROBABILITY == 1.0, \
    "Initial immune and susceptible probabilities must sum to 1.0"